### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by gugonzalez1409** [ShivinDass/NEAT-Mario#1]
Hello, im trying to run your code but  im getting this error:
super(SuperMarioBrosEnv, self).__init__(rom,
TypeError: __init__() got an unexpected keyword argument 'frames_per_step'

could you please provide a requirements.txt or the specific versions used of the packages used?

Thx :D

**Comment by ShivinDass** [comment]
This project is pretty old and I don't really remember the exact versions but you should be safe to use the version 4.0.0 of [gym-super-mario-bros](https://github.com/Kautenja/gym-super-mario-bros/releases/tag/4.0.0) and version 2.0.0 for [nes-py](https://github.com/Kautenja/nes-py/tree/2.0.0).

You might have to play around with versions around these values but the above error should be resolved if you used these exact versions.

**Comment by gugonzalez1409** [comment]
thank you, i finally made it work using gym 0.11.0, gym-super-mario-bros 4.0.2 and nes_py 2.0.2 :D
